version: '3'
services:
  windbreaker:
    build:
      context: ./repos/windbreaker
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SERVICE_ENVIRONMENT: docker
    volumes:
      - ./repos/windbreaker:/usr/windbreaker
      - /usr/windbreaker/node_modules
    command: npm start
  rss-watcher:
    build:
      context: ./repos/rss-watcher
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./repos/rss-watcher:/usr/rss-watcher
      - /usr/rss-watcher/node_modules
    command: npm start
  npm-watcher:
    build:
      context: ./repos/npm-watcher
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./repos/npm-watcher:/usr/npm-watcher
      - /usr/npm-watcher/node_modules
    command: npm start
  postgres:
    image: 'postgres:9.6.3-alpine'
    ports:
      - 5432
  rabbitmq:
    image: 'rabbitmq:3.6.10-alpine'
    ports:
      - 5672
