#cloud-config
coreos:
  units:
    - name: amazon-ecs-agent.service
      command: start
      runtime: true
      content: |
        [Unit]
        Description=Amazon ECS Agent
        After=docker.service
        Requires=docker.service
        Requires=network-online.target
        After=network-online.target

        [Service]
        Environment=ECS_CLUSTER=${ecs_cluster}
        Environment=ECS_LOGLEVEL=${ecs_loglevel}
        Environment=ECS_CHECKPOINT=${ecs_checkpoint}
        ExecStartPre=-/usr/bin/docker kill ecs-agent
        ExecStartPre=-/usr/bin/docker rm ecs-agent
        ExecStartPre=/usr/bin/docker pull amazon/amazon-ecs-agent
        ExecStart=/usr/bin/docker run --name ecs-agent \
          --env=ECS_CLUSTER=$${ECS_CLUSTER} \
          --env=ECS_LOGLEVEL=$${ECS_LOGLEVEL} \
          --env=ECS_CHECKPOINT=$${ECS_CHECKPOINT} \
          --publish=127.0.0.1:51678:51678 \
          --volume=/var/run/docker.sock:/var/run/docker.sock \
          --volume=/var/lib/aws/ecs:/data \
          amazon/amazon-ecs-agent
        ExecStop=/usr/bin/docker stop ecs-agent

